export type MENTORING_APPLICATION_STATUS =
  | 'APPROVED'
  | 'REJECTED'
  | 'PENDING'
  | 'COMPLETE';

export enum MENTORING_APPLICATION_STATUS_ENUM {
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  PENDING = 'PENDING',
  COMPLETE = 'COMPLETE',
}
